Fix default.xml.
Fix a typo for swift-nio.
Use main for swift-testing because it doesn't have release branches.

apple/swift-testing:
fatal: couldn't find remote ref refs/heads/release/6.0
apple/swift-testing: sleeping 4.0 seconds before retrying
fatal: couldn't find remote ref refs/heads/release/6.0
error: Cannot fetch apple/swift-testing from https://github.com/apple/swift-testing
Fetching: 100% (2/2), done in 10.012s
error: Cannot checkout apple/swift-nio: ManifestInvalidRevisionError: revision release/6.0 in apple/swift-nio not found